baseurl = "https://pawelsobala.netlify.com"
publishdir = "docs"
theme = "cocoa-eh-hugo-theme"
builddrafts = true
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
author = "Pawel Sobala"
title = "Pawel Sobala"
disqusshortname = ""
pluralizelisttitles = false
disableKinds = ["taxonomy", "taxonomyTerm"]
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]


[taxonomies]
# Use singular rather than plural for default taxonomies
tag = "tags"
category = "category"

#[permalinks]
#blog = "blog/:slug/"

[params]
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "A blog by Pawel Sobala"
# copyright = "Copyright © 2020-{year} Pawel Sobala"
copyright = "Copyright © 2020 Pawel Sobala"
copyrightUrl = "https://creativecommons.org/licenses/by-sa/4.0/"
logofile = "img/logo.png"
faviconfile = "img/favicon.ico"
highlightjs = true
# options for highlight.js (version, additional languages, and theme)
highlightjsVersion = "9.11.0"
highlightjsCDN = "https://cdn.bootcss.com"
highlightjsLang = ["r", "yaml"]
highlightjsTheme = "github"
progressively = true
latestpostcount = 5
share = true
share_on_googleplus = false
share_on_facebook = false
share_on_instagram = false
github = "pawelsobala"
twitter = "pawel_sobala"
#linkedin = "john-example-aa80ue8è"
#email = "you@example.com"
usesmallsummarycard = true
posts_navigation = true
social_banner = "img/logo.png"
small_banner_logo = false

[params.utteranc]
enable = true
repo = "mtn/cocoa-eh-hugo-theme"
issueTerm = "title"

[params.colors]
identifier = "#527fc1f"
identifier_dark = "#1a3152"
trivial = "#6a7a8b"
foreground = "#181d2a"
background = "#f9f9f9"
background_dark = "#282a36"
code = "#87a5d2"
type = "#97d28b"
special = "#ffcb8d"
value = "#96c2d7"
statement = "#ff8e91"
