baseurl = "https://pawelsobala.netlify.com"
author = "Pawel Sobala"
title = "Pawel Sobala"
publishdir = "docs"
contentdir = "content"
layoutdir = "layouts"
languageCode = "en-US"
theme = "cocoa-eh-hugo-theme"
builddrafts = true
canonifyurls = true
enableEmoji = true
pluralizelisttitles = false
disqusshortname = "pawelsobala"
googleAnalytics = "UA-156020229-1"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]

[permalinks]
blog = "blog/:slug/"

[params]
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "A blog by Pawel Sobala"
# copyright = "Copyright © 2020-{year} Pawel Sobala"
copyright = "Copyright © 2020 Pawel Sobala"
copyrightUrl = "https://creativecommons.org/licenses/by-sa/4.0/"
logofile = "img/logo.png"
faviconfile = "img/favicon.ico"
highlightjs = true
# options for highlight.js (version, additional languages, and theme)
highlightjsVersion = "9.11.0"
highlightjsCDN = "https://cdn.bootcss.com"
highlightjsLang = ["r", "yaml"]
highlightjsTheme = "github"
progressively = true
latestpostcount = 5
share = true
github = "pawelsobala"
twitter = "pawel_sobala"
linkedin = "pawel-sobala-17560310b"
posts_navigation = true
social_banner = "img/logo.png"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"


[params.utteranc]
enable = true
repo = "mtn/cocoa-eh-hugo-theme"
issueTerm = "title"

[params.colors]
identifier = "#527fc1f"
identifier_dark = "#1a3152"
trivial = "#6a7a8b"
foreground = "#181d2a"
background = "#f9f9f9"
background_dark = "#282a36"
code = "#87a5d2"
type = "#97d28b"
special = "#ffcb8d"
value = "#96c2d7"
statement = "#ff8e91"